### ISSUE TITLE
update icon set/ icon in "/icons/*"

### ISSUE THREAD

**Issue by baboon-king** [iconify/api#21]
Guys, I would like to provide some modification related functionality to the custom icon in "https://github.com/iconify/api/tree/main/icons", such as

1. add a new icon set to it
2. delete an icon set
3. add a new icon to an icon set
Roughly like this

I came up with the following

1. PR to https://github.com/iconify/api
But I don't think that's a good idea, it breaks the /iconify/api streamlining.

2. use separate code for this. iconify/api to extend new routes.

3. use a new service to do this without modifying any of the behavior of /iconify/api.

Both iconify/api and the new service are eligible for the https://github.com/iconify/api/tree/main/icons directory.

I'd like to get some other inspiration. Thanks to all!

**Comment by baboon-king** [comment]
I have finalized the program and if anyone is interested, they can contact me.

**Comment by BTBMan** [comment]
@baboon-king Hi, What did you do for this? I have the same needs.

**Comment by baboon-king** [comment]
@BTBMan Looks like we're speaking the same language. Email me your "WeChat" Number or other

**Comment by BTBMan** [comment]
@BTBMan Yes, I've seen you many times. WeChat is also in my profile. `WY200J`
