### ISSUE TITLE
return 404 status code (not text) if icon not found

### ISSUE THREAD

**Issue by tacman** [iconify/api#30]
![image](https://github.com/user-attachments/assets/32904b12-77db-49e7-b0f8-45ff9a7b6655)

Instead of returning a status code 200 and a text response of "404", could you change it to return an actual 404 response?  Otherwise, application that integrate this have to handle the situation in a very non-standard way.

Thanks.

**Comment by cyberalien** [comment]
Fixed.

It will take few days to deploy fix, API deployment and server maintenance is not fully automated.

**Comment by cyberalien** [comment]
All servers are now running fixed version.
